// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJXm9HaK_uiXReoDwHEgrtbWSdL9oFTMY',
    appId: '1:420625779635:web:052f754677b538475a59c6',
    messagingSenderId: '420625779635',
    projectId: 'event-management-845935',
    authDomain: 'event-management-845935.firebaseapp.com',
    storageBucket: 'event-management-845935.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC14Qm6-jmuOtnmdtRpERG3rHmmOlGMnBo',
    appId: '1:420625779635:android:2fb0791f87e5b18b5a59c6',
    messagingSenderId: '420625779635',
    projectId: 'event-management-845935',
    storageBucket: 'event-management-845935.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9mixozWknhzPL8D7Vkp1UrA9vtX47Xrw',
    appId: '1:420625779635:ios:2fd8dcd59f757b0a5a59c6',
    messagingSenderId: '420625779635',
    projectId: 'event-management-845935',
    storageBucket: 'event-management-845935.appspot.com',
    iosBundleId: 'com.example.eventManagement',
  );

}